export const mockAssessmentResult = {
  monthlyRevenue: 425000,
  netCashFlow: 88200,
  safeLoanBand: '₹5L - ₹8L',
  confidenceScore: 0.92,
  locationTier: 'Tier 1 - Urban Core',
  geoMultiplier: 1.15,
  peerBenchmarkPercentile: 78,
  fraudStatus: 'No Flags Detected',
  reviewRoute: 'Auto Approved',
  featureContributions: [
    { feature: 'Shelf Density', value: 0.34 },
    { feature: 'Product Count / SKU Diversity', value: 0.28 },
    { feature: 'Supplier Bill Validation', value: 0.12 },
    { feature: 'Geo Multiplier', value: 0.22 },
    { feature: 'Confidence Adjustment', value: -0.04 },
  ],
  riskFlags: [
    {
      title: 'Address Verification',
      description: 'Store address matches registered business location',
      severity: 'cleared' as const,
    },
    {
      title: 'Inventory Staging',
      description: 'Product density consistent with store size and location',
      severity: 'cleared' as const,
    },
    {
      title: 'Vision vs Geo Alignment',
      description: 'High inventory detected in premium location - validated',
      severity: 'low' as const,
    },
    {
      title: 'Entity Conflict Check',
      description: 'No duplicate or conflicting business registrations found',
      severity: 'cleared' as const,
    },
    {
      title: 'Confidence Penalty',
      description: 'Minor lighting variance in 1 of 4 images - minimal impact',
      severity: 'low' as const,
    },
  ],
  revenueTrend: [
    { month: 'Oct', revenue: 380000 },
    { month: 'Nov', revenue: 395000 },
    { month: 'Dec', revenue: 410000 },
    { month: 'Jan', revenue: 405000 },
    { month: 'Feb', revenue: 420000 },
    { month: 'Mar', revenue: 425000 },
  ],
  visionFeatures: {
    total_products_detected: 247,
    total_bbox_area: 892400,
    total_image_area: 3456000,
    overall_shelf_density_index: 0.258,
    avg_detections_per_image: 61.75,
    image_count: 4,
  },
  fraud_flags: ['No fraud indicators detected'],
  raw_metadata: {
    mode: 'api',
    lat: 18.5204,
    lon: 73.8567,
    processed_images: 4,
  },
}

export const mockDashboardData = {
  kpis: {
    totalAssessments: 1247,
    averageConfidence: 0.84,
    flaggedCases: 43,
    averageLoanBand: '₹4.2L',
  },
  assessmentsOverTime: [
    { month: 'Oct', count: 185 },
    { month: 'Nov', count: 198 },
    { month: 'Dec', count: 215 },
    { month: 'Jan', count: 207 },
    { month: 'Feb', count: 223 },
    { month: 'Mar', count: 219 },
  ],
  statusSplit: {
    autoApproved: 892,
    manualReview: 312,
    flagged: 43,
  },
  recentAssessments: [
    {
      id: 'KF-2024-1247',
      storeName: 'Sharma General Store',
      locality: 'Koregaon Park',
      city: 'Pune',
      revenue: 425000,
      confidence: 0.92,
      status: 'Auto Approved',
      date: '2024-03-15',
    },
    {
      id: 'KF-2024-1246',
      storeName: 'Patel Kirana',
      locality: 'Shivaji Nagar',
      city: 'Pune',
      revenue: 385000,
      confidence: 0.78,
      status: 'Manual Review',
      date: '2024-03-15',
    },
    {
      id: 'KF-2024-1245',
      storeName: 'Gupta Provisions',
      locality: 'Kothrud',
      city: 'Pune',
      revenue: 295000,
      confidence: 0.88,
      status: 'Auto Approved',
      date: '2024-03-14',
    },
    {
      id: 'KF-2024-1244',
      storeName: 'Khan Store',
      locality: 'Camp Area',
      city: 'Pune',
      revenue: 510000,
      confidence: 0.65,
      status: 'Flagged',
      date: '2024-03-14',
    },
    {
      id: 'KF-2024-1243',
      storeName: 'Desai Mart',
      locality: 'Baner',
      city: 'Pune',
      revenue: 445000,
      confidence: 0.91,
      status: 'Auto Approved',
      date: '2024-03-14',
    },
  ],
}

export const mockPortfolioData = [
  {
    caseId: 'KF-2024-1247',
    storeName: 'Sharma General Store',
    locality: 'Koregaon Park',
    city: 'Pune',
    revenueEstimate: 425000,
    netCashFlow: 88200,
    loanBand: '₹5L - ₹8L',
    confidence: 0.92,
    riskTier: 'Low',
    status: 'Auto Approved',
    lastUpdated: '2024-03-15 14:32',
  },
  {
    caseId: 'KF-2024-1246',
    storeName: 'Patel Kirana',
    locality: 'Shivaji Nagar',
    city: 'Pune',
    revenueEstimate: 385000,
    netCashFlow: 72400,
    loanBand: '₹4L - ₹6L',
    confidence: 0.78,
    riskTier: 'Medium',
    status: 'Manual Review',
    lastUpdated: '2024-03-15 11:18',
  },
  {
    caseId: 'KF-2024-1245',
    storeName: 'Gupta Provisions',
    locality: 'Kothrud',
    city: 'Pune',
    revenueEstimate: 295000,
    netCashFlow: 58200,
    loanBand: '₹3L - ₹5L',
    confidence: 0.88,
    riskTier: 'Low',
    status: 'Auto Approved',
    lastUpdated: '2024-03-14 16:45',
  },
  {
    caseId: 'KF-2024-1244',
    storeName: 'Khan Store',
    locality: 'Camp Area',
    city: 'Pune',
    revenueEstimate: 510000,
    netCashFlow: 95800,
    loanBand: '₹6L - ₹10L',
    confidence: 0.65,
    riskTier: 'High',
    status: 'Flagged',
    lastUpdated: '2024-03-14 13:22',
  },
  {
    caseId: 'KF-2024-1243',
    storeName: 'Desai Mart',
    locality: 'Baner',
    city: 'Pune',
    revenueEstimate: 445000,
    netCashFlow: 91200,
    loanBand: '₹5L - ₹8L',
    confidence: 0.91,
    riskTier: 'Low',
    status: 'Auto Approved',
    lastUpdated: '2024-03-14 10:05',
  },
  {
    caseId: 'KF-2024-1242',
    storeName: 'Singh Grocery',
    locality: 'Hadapsar',
    city: 'Pune',
    revenueEstimate: 325000,
    netCashFlow: 64500,
    loanBand: '₹3L - ₹5L',
    confidence: 0.82,
    riskTier: 'Low',
    status: 'Auto Approved',
    lastUpdated: '2024-03-13 15:30',
  },
  {
    caseId: 'KF-2024-1241',
    storeName: 'Reddy Stores',
    locality: 'Viman Nagar',
    city: 'Pune',
    revenueEstimate: 395000,
    netCashFlow: 78400,
    loanBand: '₹4L - ₹7L',
    confidence: 0.86,
    riskTier: 'Low',
    status: 'Auto Approved',
    lastUpdated: '2024-03-13 12:15',
  },
  {
    caseId: 'KF-2024-1240',
    storeName: 'Mehta Provisions',
    locality: 'Aundh',
    city: 'Pune',
    revenueEstimate: 275000,
    netCashFlow: 52800,
    loanBand: '₹2L - ₹4L',
    confidence: 0.74,
    riskTier: 'Medium',
    status: 'Manual Review',
    lastUpdated: '2024-03-13 09:40',
  },
]

export const mockAuditLog = [
  {
    timestamp: '2024-03-15 14:32:18',
    caseId: 'KF-2024-1247',
    event: 'Report Exported',
    details: 'PDF report generated and downloaded',
    status: 'completed',
  },
  {
    timestamp: '2024-03-15 14:31:45',
    caseId: 'KF-2024-1247',
    event: 'Recommendation Generated',
    details: 'Auto approval recommended - confidence 92%',
    status: 'completed',
  },
  {
    timestamp: '2024-03-15 14:31:22',
    caseId: 'KF-2024-1247',
    event: 'Fraud Check Completed',
    details: 'No fraud indicators detected',
    status: 'completed',
  },
  {
    timestamp: '2024-03-15 14:31:08',
    caseId: 'KF-2024-1247',
    event: 'Confidence Score Calculated',
    details: 'Final confidence: 92% (adjusted from 94%)',
    status: 'completed',
  },
  {
    timestamp: '2024-03-15 14:30:52',
    caseId: 'KF-2024-1247',
    event: 'Geo Multiplier Assigned',
    details: 'Location tier: Tier 1 Urban Core (1.15x)',
    status: 'completed',
  },
  {
    timestamp: '2024-03-15 14:30:35',
    caseId: 'KF-2024-1247',
    event: 'Supplier Bill Processed',
    details: 'Bill validated - ₹1.2L monthly procurement',
    status: 'completed',
  },
  {
    timestamp: '2024-03-15 14:30:18',
    caseId: 'KF-2024-1247',
    event: 'YOLO Inference Completed',
    details: '247 products detected across 4 images',
    status: 'completed',
  },
  {
    timestamp: '2024-03-15 14:29:55',
    caseId: 'KF-2024-1247',
    event: 'Photos Validated',
    details: '4 store photos uploaded and validated',
    status: 'completed',
  },
  {
    timestamp: '2024-03-15 14:29:32',
    caseId: 'KF-2024-1247',
    event: 'Evidence Uploaded',
    details: 'Bank statement, supplier bill, and photos received',
    status: 'completed',
  },
  {
    timestamp: '2024-03-15 14:29:10',
    caseId: 'KF-2024-1247',
    event: 'Case Created',
    details: 'New underwriting case initiated',
    status: 'completed',
  },
]
